"""Initial seed dataset of well-known Nepal hydropower projects.

IMPORTANT: These figures come from general public knowledge, NOT from a verified source pull.
Capacities, districts and rough dates are usually right; coordinates are approximate (~5-10 km);
costs and energy figures are rounded. Every row is loaded with data_reliability="seed-unverified".
Fields that are not confidently known are left as None. Verify against DoED / NEA annual reports
before relying on any number, and overwrite via `import-csv` as verified data arrives.
"""
from .models import ProjectStatus as S, ProjectType as T, TurbineType as TT

SEED_PROJECTS = [
    dict(project_id="HP_001", project_name_en="Upper Tamakoshi", project_name_np="माथिल्लो तामाकोशी",
         capacity_mw=456.0, status=S.OPERATIONAL, project_type=T.PEAKING_ROR, district="Dolakha",
         river="Tamakoshi", province="Bagmati", latitude=27.60, longitude=86.18, turbine_type=TT.PELTON,
         turbine_count=6, design_head_m=822, tunnel_length_m=7400, annual_energy_generation_gwh=2281,
         commissioning_year=2021, transmission_voltage_kv=220, developer="Upper Tamakoshi Hydropower Limited",
         owner="Upper Tamakoshi Hydropower Limited"),
    dict(project_id="HP_002", project_name_en="Kaligandaki A", capacity_mw=144.0, status=S.OPERATIONAL,
         project_type=T.PEAKING_ROR, district="Syangja", river="Kali Gandaki", province="Gandaki",
         latitude=27.99, longitude=83.62, turbine_type=TT.FRANCIS, turbine_count=3, design_head_m=115,
         annual_energy_generation_gwh=842, commissioning_year=2002, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority"),
    dict(project_id="HP_003", project_name_en="Middle Marsyangdi", capacity_mw=70.0, status=S.OPERATIONAL,
         project_type=T.PEAKING_ROR, district="Lamjung", river="Marsyangdi", province="Gandaki",
         latitude=28.24, longitude=84.39, turbine_type=TT.FRANCIS, turbine_count=2,
         annual_energy_generation_gwh=398, commissioning_year=2008, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority"),
    dict(project_id="HP_004", project_name_en="Marsyangdi", capacity_mw=69.0, status=S.OPERATIONAL,
         project_type=T.PEAKING_ROR, district="Tanahun", river="Marsyangdi", province="Gandaki",
         latitude=27.95, longitude=84.50, turbine_type=TT.FRANCIS, turbine_count=3,
         annual_energy_generation_gwh=462, commissioning_year=1989, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority"),
    dict(project_id="HP_005", project_name_en="Kulekhani I", capacity_mw=60.0, status=S.OPERATIONAL,
         project_type=T.RESERVOIR, district="Makwanpur", river="Kulekhani", province="Bagmati",
         latitude=27.60, longitude=85.15, turbine_type=TT.PELTON, turbine_count=2, design_head_m=550,
         annual_energy_generation_gwh=165, commissioning_year=1982, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority", notes="Nepal's only large seasonal storage reservoir."),
    dict(project_id="HP_006", project_name_en="Kulekhani II", capacity_mw=32.0, status=S.OPERATIONAL,
         project_type=T.RESERVOIR, district="Makwanpur", river="Kulekhani", province="Bagmati",
         latitude=27.62, longitude=85.14, commissioning_year=1986, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority"),
    dict(project_id="HP_007", project_name_en="Trishuli", capacity_mw=24.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Nuwakot", river="Trishuli", province="Bagmati",
         latitude=27.92, longitude=85.15, commissioning_year=1967, developer="Nepal Electricity Authority",
         owner="Nepal Electricity Authority"),
    dict(project_id="HP_008", project_name_en="Chilime", capacity_mw=22.1, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Rasuwa", river="Trishuli", province="Bagmati",
         latitude=28.20, longitude=85.30, turbine_type=TT.PELTON, turbine_count=2, commissioning_year=2003,
         developer="Chilime Hydropower Company", owner="Chilime Hydropower Company"),
    dict(project_id="HP_009", project_name_en="Khimti I", capacity_mw=60.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Dolakha", river="Khimti", province="Bagmati",
         latitude=27.59, longitude=86.06, turbine_type=TT.PELTON, turbine_count=2, design_head_m=660,
         annual_energy_generation_gwh=350, commissioning_year=2000, developer="Himal Power Limited",
         owner="Himal Power Limited"),
    dict(project_id="HP_010", project_name_en="Upper Bhotekoshi", capacity_mw=45.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Sindhupalchok", river="Bhote Koshi", province="Bagmati",
         latitude=27.85, longitude=85.92, commissioning_year=2001, developer="Bhote Koshi Power Company",
         owner="Bhote Koshi Power Company"),
    dict(project_id="HP_011", project_name_en="Kabeli-A", capacity_mw=37.6, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Panchthar", river="Kabeli", province="Koshi",
         latitude=27.30, longitude=87.75, commissioning_year=2018, developer="Kabeli Energy Limited",
         owner="Kabeli Energy Limited", notes="Co-financed by multilateral lenders (per project docs)."),
    dict(project_id="HP_012", project_name_en="Mai Khola", capacity_mw=22.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Ilam", river="Mai", province="Koshi",
         latitude=26.97, longitude=87.87, commissioning_year=2018, developer="Sanima Mai Hydropower",
         owner="Sanima Mai Hydropower"),
    # HP_013 "Upper Hewa Khola 14.9 MW / Arun Valley" removed: DoED lists Upper Hewa as 8.5 MW by Upper Hewa Khola Hydropower Co (14.9 MW is
    # Hewa Khola-A in Panchthar), and nothing ties Arun Valley to a Hewa project.
    dict(project_id="HP_014", project_name_en="Ridi Khola", capacity_mw=2.4, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Gulmi", province="Lumbini", commissioning_year=2012,
         developer="Ridi Hydropower Development Company", owner="Ridi Hydropower Development Company"),
    dict(project_id="HP_015", project_name_en="Rasuwagadhi", capacity_mw=111.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Rasuwa", river="Trishuli", province="Bagmati",
         latitude=28.27, longitude=85.32, commissioning_year=2022, developer="Chilime Hydropower Company",
         notes="Developed by a Chilime-linked company; verify owner and commissioning date."),
    dict(project_id="HP_016", project_name_en="Upper Trishuli 3A", capacity_mw=60.0, status=S.OPERATIONAL,
         project_type=T.RUN_OF_RIVER, district="Nuwakot", river="Trishuli", province="Bagmati",
         latitude=28.05, longitude=85.15, commissioning_year=2018, developer="Nepal Electricity Authority",
         notes="Verify commissioning year and owning entity."),

    # Under construction
    dict(project_id="HP_017", project_name_en="Arun-3", capacity_mw=900.0, status=S.UNDER_CONSTRUCTION,
         project_type=T.PEAKING_ROR, district="Sankhuwasabha", river="Arun", province="Koshi",
         latitude=27.55, longitude=87.25, estimated_project_cost_usd=1.04e9,
         developer="SJVN Arun-3 Power Development Company",
         owner="SJVN Arun-3 Power Development Company", notes="Indian-developer project; verify schedule."),
    dict(project_id="HP_018", project_name_en="Tanahu Hydropower", capacity_mw=140.0,
         status=S.UNDER_CONSTRUCTION, project_type=T.PEAKING_ROR, district="Tanahun", river="Seti",
         province="Gandaki", latitude=27.95, longitude=84.20, annual_energy_generation_gwh=587,
         estimated_project_cost_usd=5.05e8, developer="Tanahu Hydropower Limited",
         owner="Tanahu Hydropower Limited", notes="Multilateral-financed; verify schedule and cost."),

    # Planned / large strategic
    dict(project_id="HP_019", project_name_en="Budhigandaki", capacity_mw=1200.0, status=S.PLANNED,
         project_type=T.RESERVOIR, district="Gorkha", river="Budhi Gandaki", province="Gandaki",
         latitude=28.15, longitude=84.90, developer="Government of Nepal",
         notes="Storage project; financing model has changed several times."),
    dict(project_id="HP_020", project_name_en="Upper Karnali", capacity_mw=900.0, status=S.PLANNED,
         project_type=T.RUN_OF_RIVER, district="Dailekh", river="Karnali", province="Karnali",
         latitude=29.00, longitude=81.60, developer=None, notes="Long-running project; verify current developer/status."),
    dict(project_id="HP_021", project_name_en="West Seti", capacity_mw=750.0, status=S.PLANNED,
         project_type=T.RESERVOIR, district="Bajhang", river="Seti (West)", province="Sudurpashchim",
         latitude=29.20, longitude=81.00, notes="Verify current developer/status."),
    dict(project_id="HP_022", project_name_en="Dudhkoshi", capacity_mw=635.0, status=S.PLANNED,
         project_type=T.STORAGE, district="Solukhumbu", river="Dudh Koshi", province="Koshi",
         latitude=27.35, longitude=86.68, developer="Nepal Electricity Authority", notes="Verify status."),
    dict(project_id="HP_023", project_name_en="Upper Arun", capacity_mw=1061.0, status=S.PLANNED,
         project_type=T.RESERVOIR, district="Sankhuwasabha", river="Arun", province="Koshi",
         latitude=27.65, longitude=87.30, developer="Nepal Electricity Authority", notes="Verify status."),
]
